apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: auth
type: Opaque
stringData:
  POSTGRES_DB: authdb
  POSTGRES_USER: authuser
  # Замените на надёжный пароль перед деплоем
  POSTGRES_PASSWORD: "ChangeMe_SecurePassword_123!"
