apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: auth
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  # ClusterIP — доступен только внутри кластера
  type: ClusterIP
